### ISSUE TITLE
Career Manager Tracking & Auto-Spawn for Custom Locos

### ISSUE THREAD

**Issue by katycat5e** [katycat5e/DVCustomCarLoader#45]
- [x] Add a settings option to enable fees for player-spawned locomotives
- [x] Setting on TrainCarSetup to define locations for random spawning
- [x] Add custom locomotives into loco spawn locations system
